name: bottle_note_app
description: "bottle_note_flutter_application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  device_info_plus: ^9.0.3
  uuid: ^3.0.7
  shared_preferences: ^2.2.0

flutter:

  uses-material-design: true
